### ISSUE TITLE
Tapable.plugin is deprecated.

### ISSUE THREAD

**Issue by yagobski** [o15y/staart-ui#261]
There is problem with this library

ERROR  (node:78890) DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead

**Comment by AnandChowdhary** [comment]
This is just a warning message part of Nuxt.js. It shouldn't affect the app, and in the next major version of Nuxt.js's PWA module, it should be fixed: https://github.com/nuxt-community/pwa-module/issues/120.
