### ISSUE TITLE
Best practices to integrate Staart-ui with Staart?

### ISSUE THREAD

**Issue by Decntdefalt** [o15y/staart-ui#70]
This looks like a great project, but I’m having some difficulties understanding how to integrate this rep with Staart based on the information given.

Is it as simple for me to just start both project on their own assigned ports? (Just for dev purposes)
If I run Staart-ui on port on any random port, must I then change anything in the Staart backend repository?

**Comment by AnandChowdhary** [comment]
Hi @Decntdefalt, thanks for opening this issue. It seems like you were able to figure it out.

However, I think you're absolutely right and I will being working on a thorough documentation about how both Staart and Staart UI work, individually and together.

**Comment by AnandChowdhary** [comment]
@all-contributors Add @AnandChowdhary for code, docs, design
